version: '3.8'

services:
  web:
    image: meeting-helper/meeting-helper-docker-image-1:latest
    depends_on:
      - meeting-helper-postgres
    ports:
      - 5003:80
    networks:
      - net
  
  meeting-helper-postgres:
    container_name: meeting-helper-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5433:5433"
    volumes:
      - meeting-helper-postgres-volume:/var/lib/postgresql/data
    networks:
      - net

volumes:
  meeting-helper-postgres-volume:

networks:
  net:
    driver: bridge